export const USER_GOOGLE_SIGNIN_REQUEST = 'USER_GOOGLE_SIGNIN_REQUEST';
export const USER_GOOGLE_SIGNIN_SUCCESS = 'USER_GOOGLE_SIGNIN_SUCCESS';
export const USER_GOOGLE_SIGNIN_ERROR = 'USER_GOOGLE_SIGNIN_ERROR';

export const USER_FACEBOOK_SIGNIN_REQUEST = 'USER_FACEBOOK_SIGNIN_REQUEST';
export const USER_FACEBOOK_SIGNIN_SUCCESS = 'USER_FACEBOOK_SIGNIN_SUCCESS';
export const USER_FACEBOOK_SIGNIN_ERROR = 'USER_FACEBOOK_SIGNIN_ERROR';

export const USER_SIGNOUT = 'USER_SIGNOUT';